# ----------------------------------
# Pterodactyl .NET Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ubuntu:focal

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"
RUN apt update -y && apt upgrade -y && apt full-upgrade -y
apt install wget snapd curl gnupg -y
snap install dotnet-runtime-31

RUN adduser --disabled-password --gecos "" --home /home/container container

ENV  USER=container HOME=/home/container

USER container

WORKDIR /home/container

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
