# ----------------------------------
# Pterodactyl .NET Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ubuntu:focal

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"
RUN apt update && apt install wget -y
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb
RUN apt update && apt install apt-transport-https dotnet-sdk-3.1 -y
RUN dotnet --version

RUN adduser --disabled-password --gecos "" --home /home/container container

ENV  USER=container HOME=/home/container

USER container

WORKDIR /home/container

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
