# ----------------------------------
# Pterodactyl Plutonium Egg Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ghcr.io/garycraft/ptero-wine:dev

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"

USER root
ENV WINEDEBUG=fixme-all
ENV WINEARCH=win64
ENV WINEPREFIX=/home/container/.wine
#ENV WINEDLLOVERRIDES=mscoree
ENV DISPLAY=:0
#ENV DISPLAY_WIDTH=1024 DISPLAY_HEIGHT=768 DISPLAY_DEPTH=16
#ENV AUTO_UPDATE=1
#ENV XVFB=1

COPY checkupdater.sh /checkupdater.sh
#Make sure the script is executable by anyone
RUN chmod ugo+x /checkupdater.sh

ENV  USER=container HOME=/home/container/
USER container
WORKDIR /home/container/

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]