# ----------------------------------
# Pterodactyl Plutonium Egg Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM garycraft/pterowine:ubuntu

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"

ENV WINEDEBUG=fixme-all
ENV WINEARCH=win64
ENV WINEPREFIX=/home/container/.wine

COPY checkupdater.sh /checkupdater.sh
RUN chmod +x /checkupdater.sh

ENV  USER=container HOME=/home/container/
USER container
WORKDIR /home/container/

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]