# ----------------------------------
# Pterodactyl Wine Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ubuntu:focal

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"

ENV WINEDEBUG=fixme-all
ENV WINEARCH=win64
ENV WINEPREFIX=/home/container/.wine

RUN adduser --disabled-password --gecos "" --home /home/container container

RUN apt-get update && apt-get install wget -y && wget https://raw.githubusercontent.com/GaryCraft/ptero-plutonium/main/IMAGES/ptero-wine/installwine.sh && bash installwine.sh

ENV  USER=container HOME=/home/container

USER container

RUN winecfg

USER root

RUN mkdir /wineprefix && cp -r /home/container/.wine /wineprefix && chmod 777 /wineprefix

USER container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
