# ----------------------------------
# Pterodactyl Wine Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ubuntu:focal

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"

ENV WINEDEBUG=fixme-all
ENV WINEARCH=win64
ENV WINEPREFIX=/home/container/.wine
ENV WINEDLLOVERRIDES=mscoree,mshtml=
ENV DISPLAY=:0 DISPLAY_WIDTH=1024 DISPLAY_HEIGHT=768 DISPLAY_DEPTH=16
ENV AUTO_UPDATE=1
ENV XVFB=1

COPY installwine.sh /installwine.sh
RUN chmod +x /installwine.sh 
RUN /installwine.sh && rm /installwine.sh

RUN adduser --disabled-password --gecos "" --home /home/container container
ENV USER=container HOME=/home/container DEBIAN_FRONTEND=noninteractive
USER container
WORKDIR /home/container

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
