FROM alpine:3.10.2

# Wine 32Bit for running EXE
RUN apk add --no-cache wine=3.0.4-r1 freetype=2.10.0-r1

# Fake X11 display for headless execution
RUN apk add --no-cache xvfb-run=1.20.4-r0

# Configure Wine
RUN winecfg

#Avoid Permission Error
RUN sudo rm -rf ~/docker-data/wine && mkdir ~/docker-data/wine

# Install wget
RUN apk add --no-cache wget=1.20.3-r0 && ln -s /usr/bin/wine64 /usr/bin/wine

# Download Mono
RUN wget -P /mono http://dl.winehq.org/wine/wine-mono/4.9.3/wine-mono-4.9.3.msi

# Install Mono Runtime for .NET Applications
RUN wine msiexec /i /mono/wine-mono-4.9.3.msi
RUN rm -rf /mono/wine-mono-4.9.3.msi



COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/sh", "/entrypoint.sh"]
