# ----------------------------------
# Pterodactyl Plutonium Dockerfile
# Environment: Alpine Linux 3.14.0
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM alpine:3.14.0

LABEL Author="GaryCraft@SpaceProject, <garycraft@our-space.xyz>"

RUN apk update &&\apk add wget &&\wget https://raw.githubusercontent.com/GaryCraft/ptero-plutonium/main/base-alpine/installwine.sh &&\sh installwine.sh

# RUN wget https://raw.githubusercontent.com/GaryCraft/ptero-plutonium/main/installpluto.sh &&\bash installpluto.sh

RUN apk add --no-cache --update curl ca-certificates openssl git tar bash sqlite fontconfig \
    && adduser --disabled-password --home /home/container container

USER container
ENV  USER=container HOME=/home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
