# ----------------------------------
# Pterodactyl .NET Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ubuntu:focal

LABEL maintainer="GaryCraft@SpaceProject <garycraft@our-space.xyz>"
# Updating Image to latest
RUN apt update -y && apt upgrade -y && apt full-upgrade -y
# Installing packages
apt install wget snapd curl gnupg install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev -y

# Python installation
sudo apt install python3.9
sudo apt-cache policy python3.9
python3.9 --version

# Run Environment 
RUN adduser --disabled-password --gecos "" --home /home/container container
ENV  USER=container HOME=/home/container
USER container
WORKDIR /home/container

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]

# -----------------------------------------------------------------------------
# THIS SCRIPT HAS TO BE REVEIWED AND REVISIONED. THIS IS NOT A FINISHED PRODUCT.
# THESE LINES CAN BE DELETED AFTER CODE HAS BEEN EXPIREMENTED AND REVISIONED.
#                                        - @zeropoint#9798 - wegj1@hotmail.com
# -----------------------------------------------------------------------------
