name: build images

on:
  push:
    branches: [ main ]
    paths:
    - IMAGES/**
jobs:
  build:
    name: "${{ matrix.tag }}:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
         - ptero-wine
         - ptero-dotNET
         - ptero-plutonium
    steps:
    - uses: actions/checkout@v2
    - uses : docker/setup-buildx-action@v1
      with:
          version: "v0.5.1"
          buildkitd-flags: --debug
    - uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
          context: ./IMAGES/${{ matrix.tag }}
          file: ./IMAGES/${{ matrix.tag }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/garycraft/${{ matrix.tag }}:latest
